eureka:
  instances:
    prefer-ip-addresses: true
  client:
    fetch-registry: true
    register-with-eureka: true
  service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-65623069.okta.com/oauth2/default
    default: api://default
